
# Only one "main" profile is available for now
[profile.main]
# Build command
build_command = "cargo build --release --target x86_64-unknown-linux-musl"

# Which path the binaries are copied from
binary_target = "target/x86_64-unknown-linux-musl/release"

# Binaries to copy
binaries = ["init", "rind", "example-active", "example-inactive"]

# Files to copy over
files = ["examples/services:/etc/services"]

# Busybox Setup
busybox_url = "https://busybox.net/downloads/binaries/1.19.0/busybox-x86_64"
busybox_applets = [
  "sh",
  "ls",
  "cp",
  "mkdir",
  "echo",
  "cat",
  "rm",
  "ln",
  "less",
  "clear",
  "wget",
  "vi",
  "uptime",
  "stat",
  "find",
  "dmesg"
]

# Utilities
install = [
  # glibc
  # "https://mirror.moson.org/arch/core/os/x86_64/glibc-2.43+r5+g856c426a7534-1-x86_64.pkg.tar.zst",
  # filesystem
  # "https://mirror.moson.org/arch/core/os/x86_64/filesystem-2025.10.12-1-any.pkg.tar.zst",
  # iana-etc
  # "https://mirror.moson.org/arch/core/os/x86_64/iana-etc-20260225-2-any.pkg.tar.zst",
  # linux-api-headers
  # "https://mirror.moson.org/arch/core/os/x86_64/linux-api-headers-6.19-1-x86_64.pkg.tar.zst",
  # tzdata
  # "https://mirror.moson.org/arch/core/os/x86_64/tzdata-2025c-1-x86_64.pkg.tar.zst",
  # corutils
  # "https://mirror.accum.se/mirror/archlinux/core/os/x86_64/coreutils-9.10-1-x86_64.pkg.tar.zst",
  # bash
  # "https://mirror.accum.se/mirror/archlinux/core/os/x86_64/bash-5.3.9-1-x86_64.pkg.tar.zst",
  # ncurses
  # "https://mirror.accum.se/mirror/archlinux/core/os/x86_64/ncurses-6.6-1-x86_64.pkg.tar.zst",
  # readline
  # "https://mirror.accum.se/mirror/archlinux/core/os/x86_64/readline-8.3.003-1-x86_64.pkg.tar.zst"
]

# Use images for now, cpio is depricated
disk_mode = "image"

# Linux Image: for now we can use bzImage
linux_image = "bzImage:https://l4re.org/download/Linux-kernel/x86-64/bzImage-6.6.8"

# root= is needed for image disks
run_options = ["console=ttyS0/ root=/dev/vda rw"]
#qemu_options = { arch = "x86_64", args = [...] }

# Depricated
nodes = [
  # { path = "/dev/null", node_type = "c", major = 1, minor = 3, mode = 0o666 },
  # { path = "/dev/tty1", node_type = "c", major = 4, minor = 1, mode = 0o666 },
  # { path = "/dev/console", node_type = "c", major = 5, minor = 1, mode = 0o666 }
]
