[[service]]
name = "example-active"
exec = "/bin/example-active"
args = ["arg1", "arg2"]
restart = false

[[service]]
name = "example-inactive"
exec = "/bin/example-inactive"
args = ["arg1", "arg2"]
restart = { max_retries = 5 }
